2023-07-03 15:49:20,772: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 15:49:20,772: [11] m.main:INFO: Beginning analysis
2023-07-03 15:49:20,774: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 15:49:21,207: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 15:49:21,737: [11] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 15:49:21,745: [11] m.e.manticore:INFO: 0 alive states, 1 terminated states
2023-07-03 15:49:21,862: [11] m.c.manticore:INFO: Results in /mcore_3lv89ay6
2023-07-03 15:49:21,864: [11] m.c.manticore:INFO: Total time: 0.6518838405609131
2023-07-03 15:49:22,579: [73] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 15:49:22,579: [73] m.main:INFO: Beginning analysis
2023-07-03 15:49:22,583: [73] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 15:49:24,010: [73] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 15:49:44,767: [73] m.c.worker:ERROR: Exception in state 1: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 15:49:48,362: [73] m.e.manticore:INFO: 0 alive states, 4 terminated states
2023-07-03 15:49:48,717: [73] m.c.manticore:INFO: Results in /mcore_isli213u
2023-07-03 15:49:48,718: [73] m.c.manticore:INFO: Total time: 24.683648109436035
2023-07-03 15:49:49,514: [159] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 15:49:49,515: [159] m.main:INFO: Beginning analysis
2023-07-03 15:49:49,517: [159] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 15:49:50,979: [159] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 15:50:13,766: [159] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 15:50:15,256: [159] m.e.manticore:INFO: 0 alive states, 4 terminated states
2023-07-03 15:50:15,680: [159] m.c.manticore:INFO: Results in /mcore_mbs_vfo9
2023-07-03 15:50:15,680: [159] m.c.manticore:INFO: Total time: 24.681201457977295
