2023-07-03 16:42:22,586: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:42:22,587: [11] m.main:INFO: Beginning analysis
2023-07-03 16:42:22,592: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:42:23,141: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:42:23,585: [11] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:42:23,593: [11] m.e.manticore:INFO: 0 alive states, 1 terminated states
2023-07-03 16:42:23,733: [11] m.c.manticore:INFO: Results in /mcore_lc99fqvt
2023-07-03 16:42:23,734: [11] m.c.manticore:INFO: Total time: 0.5885941982269287
2023-07-03 16:42:24,392: [73] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:42:24,393: [73] m.main:INFO: Beginning analysis
2023-07-03 16:42:24,395: [73] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:42:25,820: [73] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:42:47,982: [73] m.c.worker:ERROR: Exception in state 7: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:42:50,173: [73] m.e.manticore:INFO: 0 alive states, 4 terminated states
2023-07-03 16:42:50,864: [73] m.c.manticore:INFO: Results in /mcore_md037r6b
2023-07-03 16:42:50,864: [73] m.c.manticore:INFO: Total time: 25.019861698150635
2023-07-03 16:42:51,566: [153] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:42:51,566: [153] m.main:INFO: Beginning analysis
2023-07-03 16:42:51,569: [153] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:42:56,223: [153] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:45:31,678: [153] m.c.worker:ERROR: Exception in state 10: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:45:44,393: [153] m.e.manticore:INFO: 0 alive states, 4 terminated states
2023-07-03 16:45:46,312: [153] m.c.manticore:INFO: Results in /mcore_pk88yewm
2023-07-03 16:45:46,312: [153] m.c.manticore:INFO: Total time: 169.9967339038849
2023-07-03 16:45:47,255: [242] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:45:47,255: [242] m.main:INFO: Beginning analysis
2023-07-03 16:45:47,257: [242] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:45:48,906: [242] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:46:09,436: [242] m.c.worker:ERROR: Exception in state 9: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:46:11,266: [242] m.e.manticore:INFO: 0 alive states, 4 terminated states
2023-07-03 16:46:11,764: [242] m.c.manticore:INFO: Results in /mcore_5faa3dfj
2023-07-03 16:46:11,764: [242] m.c.manticore:INFO: Total time: 22.837100505828857
