2023-07-03 16:50:04,456: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:50:04,456: [11] m.main:INFO: Beginning analysis
2023-07-03 16:50:04,458: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:50:05,036: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:50:05,575: [11] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:50:05,582: [11] m.e.manticore:INFO: 0 alive states, 1 terminated states
2023-07-03 16:50:05,697: [11] m.c.manticore:INFO: Results in /mcore_v0z7i7cm
2023-07-03 16:50:05,698: [11] m.c.manticore:INFO: Total time: 0.6569294929504395
2023-07-03 16:50:06,486: [73] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:50:06,487: [73] m.main:INFO: Beginning analysis
2023-07-03 16:50:06,489: [73] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:50:08,111: [73] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:50:30,728: [73] m.c.worker:ERROR: Exception in state 6: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:50:33,728: [73] m.e.manticore:INFO: 0 alive states, 4 terminated states
2023-07-03 16:50:34,117: [73] m.c.manticore:INFO: Results in /mcore_vfiuj8b3
2023-07-03 16:50:34,117: [73] m.c.manticore:INFO: Total time: 25.98990511894226
2023-07-03 16:50:34,898: [156] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:50:34,898: [156] m.main:INFO: Beginning analysis
2023-07-03 16:50:34,901: [156] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:50:39,662: [156] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:53:20,648: [156] m.c.worker:ERROR: Exception in state 2: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:53:42,300: [156] m.e.manticore:INFO: 0 alive states, 4 terminated states
2023-07-03 16:53:43,778: [156] m.c.manticore:INFO: Results in /mcore_jmjzj_ol
2023-07-03 16:53:43,778: [156] m.c.manticore:INFO: Total time: 184.027405500412
2023-07-03 16:53:44,393: [242] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:53:44,394: [242] m.main:INFO: Beginning analysis
2023-07-03 16:53:44,396: [242] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:53:45,788: [242] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:54:11,947: [242] m.c.worker:ERROR: Exception in state 9: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:54:15,135: [242] m.e.manticore:INFO: 0 alive states, 4 terminated states
2023-07-03 16:54:15,534: [242] m.c.manticore:INFO: Results in /mcore_pgygp64x
2023-07-03 16:54:15,534: [242] m.c.manticore:INFO: Total time: 29.733777046203613
