2023-07-13 02:38:22,565: [11] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-13 02:38:22,566: [11] m.main:INFO: Beginning analysis
2023-07-13 02:38:22,568: [11] m.e.manticore:INFO: Starting symbolic create contract
2023-07-13 02:38:23,053: [11] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-13 02:38:23,157: [11] m.e.manticore:INFO: 0 alive states, 2 terminated states
2023-07-13 02:38:23,306: [11] m.c.manticore:INFO: Results in /mcore_m_jmibpu
2023-07-13 02:38:23,306: [11] m.c.manticore:INFO: Total time: 0.2485952377319336
2023-07-13 02:38:23,917: [76] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-13 02:38:23,918: [76] m.main:INFO: Beginning analysis
2023-07-13 02:38:23,920: [76] m.e.manticore:INFO: Starting symbolic create contract
2023-07-13 02:38:26,468: [76] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-13 02:39:22,743: [76] m.c.worker:ERROR: Exception in state 2: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-13 02:39:34,163: [76] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01' -> 27376155845717860833342594873357525089589924219251518322086369159840883582034
2023-07-13 02:39:39,557: [76] m.e.manticore:INFO: Found a concrete globalsha3 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03' -> 109825747609387604026257694119480052437337487955339004288381632936333863410599
2023-07-13 02:42:24,476: [76] m.e.manticore:INFO: 4 alive states, 1 terminated states
2023-07-13 02:42:27,628: [76] m.e.manticore:INFO: Starting symbolic transaction: 1
