2023-07-03 16:06:13,377: [12] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:06:13,378: [12] m.main:INFO: Beginning analysis
2023-07-03 16:06:13,379: [12] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:06:13,683: [12] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:06:13,772: [12] m.e.manticore:INFO: 0 alive states, 2 terminated states
2023-07-03 16:06:13,896: [12] m.c.manticore:INFO: Results in /mcore_prg4h1h0
2023-07-03 16:06:13,896: [12] m.c.manticore:INFO: Total time: 0.20747661590576172
2023-07-03 16:06:14,603: [74] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2023-07-03 16:06:14,603: [74] m.main:INFO: Beginning analysis
2023-07-03 16:06:14,606: [74] m.e.manticore:INFO: Starting symbolic create contract
2023-07-03 16:06:16,303: [74] m.e.manticore:INFO: Starting symbolic transaction: 0
2023-07-03 16:06:16,924: [74] m.c.worker:ERROR: Exception in state 0: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2023-07-03 16:06:16,930: [74] m.e.manticore:INFO: 0 alive states, 0 terminated states
2023-07-03 16:06:16,980: [74] m.c.manticore:INFO: Results in /mcore_zcxx4_mp
2023-07-03 16:06:16,981: [74] m.c.manticore:INFO: Total time: 0.6730837821960449
